version: '3.2'

networks:
  pre-event-network:
    driver: bridge

services:

  #MYSQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./data/db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--skip-character-set-client-handshake'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: vetautet
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
    ports:
      - "3307:3306"
    networks:
      - pre-event-network

#  #Redis
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - pre-event-network

  #Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - pre-event-network

  #Grafana
  grafana:  #ID 4701
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SING_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_LOG_MOD=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - pre-event-network

  #Node exporter
  node_exporter:  #ID : 1860
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - "9100:9100"
    networks:
      - pre-event-network

  # Redis exporter
  redis-exporter: #ID 763
    image: oliver006/redis_exporter
    command:
      - '--redis.addr=redis://redis:6379'
    ports:
      - "9121:9121"
    networks:
      - pre-event-network


  # Mysql exporter
#  mysqld_exporter :
#    image: prom/mysqld-exporter
#    container_name: mysql-exporter
#    ports:
#      - "9104:9104"
#    command:
#      - '--collect.engine_innodb_status'
#      - '--collect.info_schema.processlist'
#      - '--collect.info_schema.tables'
#      - '--collect.info_schema.query_response_time'
#      - '--collect.perf_schema.file_events'
#      - '--collect.perf_schema.eventsstatements'
#      - '--collect.perf_schema.indexiowaits'
#      - '--collect.global_status'
##      - '--ignore-tables'
#      - '--config.my-cnf=/etc/mysql/.my.cnf'
#    volumes:
#      - ./mysqld-exporter/.my.cnf:/etc/mysql/.my.cnf
#    environment:
#      - DATASOURCE_NAME=root:root1234@tcp(mysql:3307)/
#    depends_on:
#      - mysql
#    networks:
#      - pre-event-network
